---
- name: Install Apache2
  hosts: 172.16.0.113
  become: true  # Enable privilege escalation (sudo)
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
        
